= Elasticsearch (non Open Distro) installation with Open Distro Security Plugin

== Description

This project performs the https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/[Standalone Elasticsearch plugin installation] which runs the Open Distro Security Plugin on top of the Open Source version of Elasticsearch. The installation is orchestrated via https://github.com/saravanan30erd/opendistro_standalone_installation[Ansible Play] and only requires Ansible and Java on the provisioner host.

This stack yields full security in a free package.

* https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/[Security Plugin Configuration]
* https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/[Security Plugin Access Control]
** Provides:
*** Users/Roles with various identity provider/directory integration points
*** Document level security
*** Field level security
*** Field level masking
*** Cross cluster search

== Testing

The local Vagrantfile will bootstrap 3 VMs (in your hypervisor of choice). Simply run 'vagrant up' (although if you're not using VirtualBox, you may have to adjust the memory setting).

Once your VMs are up (these can easily be EC2 instances), you can run the ansible play found under the opendistro_standalone_installation directory:

 ansible-playbook -i inventories/opendistro/hosts opendistro.yml -vv

Once the play is complete, you can connect to http://10.0.0.10:5601 and connect to kibana.
[source]
--
PLAY RECAP *****************************************************************************************************************************************************************
es1                        : ok=40   changed=32   unreachable=0    failed=0
es2                        : ok=22   changed=15   unreachable=0    failed=0
es3                        : ok=22   changed=15   unreachable=0    failed=0
--

== Misc Notes

This play is taken from https://github.com/saravanan30erd/opendistro_standalone_installation and customized slightly. I've added some TODOs for basic idempotency but further customization of the security plugin file would be needed.

Production instances would be managed via new inventories. 
