---

- name: Security Plugin Install | Download Opendistro Kibana security plugin {{ opendistro_security_version }}
  get_url:
    url: "{{ opendistro_security_kibana_download_url }}opendistro_security_kibana_plugin-{{ opendistro_security_version }}.zip"
    dest: "/usr/share/kibana/opendistro_security-{{ opendistro_security_version }}.zip"
  register: download

- name: Security Plugin Install | Install the Opendistro security plugin in kibana
  command: "{{ kibana_plugin_bin_path }} install file:///usr/share/kibana/opendistro_security-{{ opendistro_security_version }}.zip"
  when: download.changed
  notify: restart kibana
