---
# handlers file for elasticsearch
- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload

# Restart service and ensure it is enabled

- name: restart elasticsearch
  become: yes
  service: name=elasticsearch state=restarted enabled=yes
  when:
    - es_restart_on_change
    - es_start_service
  register: es_restarted

- name: restart kibana
  systemd: name=kibana state=restarted enabled=yes
